### ISSUE TITLE
Crash During OTA - attempt to use cleared object reference

### ISSUE THREAD

**Issue by bradmartin** [Max-Mobility/permobil-mobile#2]
```
com.tns.NativeScriptException: Attempt to use cleared object reference id=7591
    at com.tns.Runtime.getJavaObjectByID(Runtime.java:923)
    at com.tns.Runtime.callJSMethodNative(Runtime.java)
    at com.tns.Runtime.access$2300(Runtime.java:34)
    at com.tns.Runtime$3.run(Runtime.java:1140)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:6981)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

something happened with marking mode most likely. We can disable markingMode for now and see how performance goes. 

Ultimately, some changes to the bluetooth plugin code would likely prevent this from happening.

**Comment by finger563** [comment]
https://sentry.io/organizations/maxmobility/issues/784776430/?referrer=github_plugin
